In [63]:
import numpy as np
import pandas as pd
import plotly.express as px

In [64]:
data = np.load('../data/metr_la_new.npz', allow_pickle=True)

In [65]:
data['edges']

array([[  0,  37],
       [  0,  54],
       [  0, 116],
       ...,
       [206, 155],
       [206, 159],
       [206, 163]], dtype=int32)

In [66]:
dataset = data['targets']
dataset_size = len(dataset)

In [67]:
for i in range(0, len(dataset)):
    for j in range(0, len(dataset[i])):
        if np.isnan(dataset[i][j]):
            dataset[i][j] = dataset[max(i - 1, 0)][j]

In [68]:
import torch 
import random
from torch.utils.data import TensorDataset, DataLoader


In [69]:
device = "cpu" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [70]:
train_size = int(0.6 * dataset_size)
test_size =  int(0.2 * dataset_size)
vertice = 0
dataset_for_vertice = dataset[:, vertice]

In [71]:
coef = 20
pred_cnt = 12

In [72]:
samples_train = [i for i in random.sample(range(coef, int(dataset_size * 0.7)), train_size)]

X_train = [dataset_for_vertice[i - coef: i] for i in samples_train]
X_train = torch.tensor(X_train).to(device)

y_train = [dataset_for_vertice[i:i + pred_cnt] for i in samples_train]
y_train = torch.tensor(y_train).to(device)

samples_test = [i for i in random.sample(range(int(dataset_size * 0.7), dataset_size - pred_cnt), test_size)]
X_test = [dataset_for_vertice[i - coef: i] for i in samples_test]
X_test = torch.tensor(X_test).to(device)

y_test = [dataset_for_vertice[i:i + pred_cnt] for i in samples_test]
y_test = torch.tensor(y_test).to(device)

In [73]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(y_train)
print(y_test)


torch.Size([20563, 20]) torch.Size([20563, 12])
torch.Size([6854, 20]) torch.Size([6854, 12])
tensor([[65.1111, 65.2500, 63.6667,  ..., 63.7500, 64.5000, 63.8889],
        [67.1429, 64.0000, 67.0000,  ..., 67.8750, 65.6250, 66.3333],
        [62.4444, 63.6250, 63.6250,  ..., 39.7500, 56.0000, 39.6667],
        ...,
        [39.7500, 63.2500, 67.7778,  ..., 57.7500, 60.8750, 60.6250],
        [67.1250, 64.3333, 66.2500,  ..., 64.6250, 66.0000, 66.5000],
        [62.0000, 59.8750, 52.2222,  ..., 58.3333, 60.7778, 64.7500]])
tensor([[68.5714, 68.6667, 67.5000,  ..., 67.8750, 68.7500, 67.1429],
        [65.6667, 65.7500, 66.1111,  ..., 66.6667, 64.7778, 65.8889],
        [65.1250, 64.4444, 64.1250,  ..., 62.3333, 65.8750, 45.5000],
        ...,
        [65.4444, 67.2500, 61.5000,  ..., 62.1250, 66.1111, 66.1250],
        [67.1250, 68.4444, 66.6250,  ..., 67.3333, 67.1111, 66.8750],
        [61.1111, 56.0000, 62.7778,  ..., 59.7500, 62.0000, 64.2500]])


In [74]:
train_data_set = TensorDataset(X_train, y_train)
train_dataloader = DataLoader(train_data_set,
                        shuffle = True,
                        batch_size = 8)

test_data_set = TensorDataset(X_test, y_test)
test_dataloader = DataLoader(test_data_set,
                        shuffle = True,
                        batch_size = 1)

In [75]:
from torch import nn

model_1 = nn.Linear(coef, 1)
model_1.to(device)

model_1 = torch.compile(model_1)


In [76]:
optimizer = torch.optim.Adam(params = model_1.parameters(), lr = 1e-7, weight_decay=1e-5)
loss_fn = nn.L1Loss()

In [77]:
from tqdm import tqdm

In [78]:
torch.set_float32_matmul_precision('high')

In [79]:
def make_a_guess(model, X):
    ans = []
    updated_X = X
    for k in range(pred_cnt):
        ans.append(model(updated_X).to(device))
        updated_X = updated_X[:, :-1]
        updated_X = torch.cat([updated_X, ans[-1]], dim = 1)
    ans = torch.stack(ans, dim = 0).to(device)
    ans = torch.permute(ans, (1, 0, 2)).squeeze(dim = 2)
    return ans

In [80]:
epochs = 100


losses = []

for i in tqdm(range(epochs)):
    for x, y in train_dataloader:
        y_pred = make_a_guess(model = model_1, X=x)
        loss = loss_fn(y_pred, y).to(device)
        losses.append(loss.item())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


  0%|          | 0/100 [00:08<?, ?it/s]


KeyboardInterrupt: 

In [81]:
px.line(y = np.array(losses))

In [82]:
np.array(losses).mean()

126.17409753762331

In [83]:
def handle_autoregression(model_1):
    model_1.eval()
    test_losses_using_model = []
    with torch.inference_mode():
        for x, y in test_dataloader:
            y_pred = make_a_guess(model = model_1, X=x)
            loss = loss_fn(y_pred, y).to(device)
            test_losses_using_model.append(loss.item())
    return test_losses_using_model

mean_loss_using_model = np.array(handle_autoregression(model_1)).mean()
mean_loss_using_model

125.04287573196883

In [84]:
type(dataset_for_vertice)

numpy.ndarray

In [85]:
average_val = torch.tensor(dataset_for_vertice.mean())
test_losses_using_average = []

for x, y in test_dataloader:
    y_pred = torch.stack([average_val] * pred_cnt, dim = 0).unsqueeze(dim = 0).to(device)
    loss = loss_fn(y_pred, y).to(device)
    test_losses_using_average.append(loss.item())


mean_loss_using_average = np.array(test_losses_using_average).mean()
mean_loss_using_average

7.07577175496139

In [29]:
test_losses_using_last = []

for x, y in test_dataloader:
    last_val = x[:, -1]
    y_pred = torch.stack([last_val] * pred_cnt, dim = 0).unsqueeze(dim = 0).squeeze(dim = 2).to(device)
    loss = loss_fn(y_pred, y).to(device)
    test_losses_using_last.append(loss.item())


mean_loss_using_last = np.array(test_losses_using_last).mean()
mean_loss_using_last

3.202477211234284

In [30]:
from random import randint

In [27]:
test_losses_using_week_before = []
week_length = 12 * 24 * 7

for i in range(test_size):
    x = randint(week_length, dataset_for_vertice.shape[0] - 1)
    y = torch.tensor(dataset_for_vertice[x]).to(device)
    y_pred = torch.tensor(dataset_for_vertice[x - week_length]).to(device)
    loss = loss_fn(y_pred, y).to(device)
    test_losses_using_week_before.append(loss.item())

mean_loss_using_week_before = np.array(test_losses_using_week_before).mean()
mean_loss_using_week_before

4.602694672400032

In [86]:
from pandas import DataFrame as df

In [87]:
print("Average error for next hour guesses")
print(f"mean_loss_using_average: {mean_loss_using_average}")
print(f"mean_loss_using_last: {mean_loss_using_last}")
print(f"mean_loss_using_week_before :{mean_loss_using_week_before}")
print(f"mean_loss_using_model: {mean_loss_using_model}")


Average error for next hour guesses
mean_loss_using_average: 7.07577175496139


NameError: name 'mean_loss_using_last' is not defined

In [88]:
comparison = df({"mean_loss_using_average": [mean_loss_using_average.item()],
                 "mean_loss_using_last": [mean_loss_using_last.item()],
                 "mean_loss_using_week_before": [mean_loss_using_week_before.item()],
                 "mean_loss_using_model": [mean_loss_using_model.item()]})
comparison.T

NameError: name 'mean_loss_using_last' is not defined

In [32]:
! pip install catboost

  Using cached catboost-1.2.7-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
  Using cached graphviz-0.20.3-py3-none-any.whl.metadata (12 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 4.2 MB/s eta 0:00:0000:0100:01


In [89]:
from catboost import CatBoostRegressor

In [90]:
cat = CatBoostRegressor(iterations = 1000, depth=10, l2_leaf_reg=3)

In [91]:
X_train = pd.DataFrame(np.array(X_train))
y_train = pd.DataFrame(np.array(y_train)[:, 0])

cat.fit(X_train, y_train,)

0:	learn: 11.4509024	total: 31.4ms	remaining: 31.4s
1:	learn: 11.1613968	total: 58.2ms	remaining: 29s
2:	learn: 10.8927717	total: 80.9ms	remaining: 26.9s
3:	learn: 10.6166318	total: 101ms	remaining: 25.1s
4:	learn: 10.3533258	total: 121ms	remaining: 24s
5:	learn: 10.1009615	total: 138ms	remaining: 22.9s
6:	learn: 9.8553997	total: 155ms	remaining: 21.9s
7:	learn: 9.6235974	total: 171ms	remaining: 21.2s
8:	learn: 9.3901800	total: 184ms	remaining: 20.3s
9:	learn: 9.1753782	total: 198ms	remaining: 19.6s
10:	learn: 8.9613669	total: 211ms	remaining: 19s
11:	learn: 8.7498265	total: 224ms	remaining: 18.5s
12:	learn: 8.5510690	total: 239ms	remaining: 18.1s
13:	learn: 8.3546430	total: 255ms	remaining: 17.9s
14:	learn: 8.1633824	total: 271ms	remaining: 17.8s
15:	learn: 7.9824800	total: 286ms	remaining: 17.6s
16:	learn: 7.8088504	total: 300ms	remaining: 17.4s
17:	learn: 7.6378121	total: 314ms	remaining: 17.2s
18:	learn: 7.4694621	total: 327ms	remaining: 16.9s
19:	learn: 7.3083684	total: 339ms	rema

In [92]:
def handle_autoregression_for_catboost(time_line: list, 
                                       ethalon:list,
                                       epochs:int,
                                       model_cat):
    answer = []
    time_line = time_line.tolist()
    for i in range(0, epochs):
        next = model_cat.predict(time_line)
        answer.append(next)
        time_line.append(next)
        time_line[1:]
    return (abs(np.array(answer) - np.array(ethalon))).mean()

In [96]:
result = []

for x, y in zip(np.array(X_test), np.array(y_test)):
    result.append(handle_autoregression_for_catboost(x, 
                                                 y, 
                                                 epochs = 12, 
                                                 model_cat = cat))

px.line(y = result)

In [95]:
graph = {}
for edge in data['edges']:
    graph[edge[0]] = []
for edge in data['edges']:
    graph[edge[0]].append(edge[1])

In [97]:
timestamps = pd.date_range(start=data["first_timestamp_datetime"].item(),
                           end=data["last_timestamp_datetime"].item(),
                           freq="5min",
                           )

In [100]:
import sys
sys.path

['/home/theorcos239/spatiotemporal_analysis/notebooks/features.py',
 '/home/theorcos239/spatiotemporal_analysis/notebooks/features.py',
 '/home/theorcos239/spatiotemporal_analysis/notebooks/features.py',
 '/usr/lib/python312.zip',
 '/usr/lib/python3.12',
 '/usr/lib/python3.12/lib-dynload',
 '',
 '/home/theorcos239/spatiotemporal_analysis/.venv/lib/python3.12/site-packages',
 '/home/theorcos239/spatiotemporal_analysis/.venv/lib/python3.12/site-packages/setuptools/_vendor']